### ISSUE TITLE
Почему это существует?

### ISSUE THREAD

**Issue by FeeeeK** [mrMiiao/vkbottle4_custom#1]
Мне правда хочется узнать ответ на этот вопрос...

**Comment by FeeeeK** [comment]
И еще советую ознакомиться с лицензией vkbottle
https://github.com/vkbottle/vkbottle/blob/16f4cbd9b6603e58e9d82083fa452ffe2e7fbd93/LICENSE#L13-L14
согласно ей, вы не можете просто скопировать код в свой репозиторий, удалив этот файл.

**Comment by mrMiiao** [comment]
> И еще советую ознакомиться с лицензией vkbottle
> https://github.com/vkbottle/vkbottle/blob/16f4cbd9b6603e58e9d82083fa452ffe2e7fbd93/LICENSE#L13-L14
> согласно ей, вы не можете просто скопировать код в свой репозиторий, удалив этот файл.

Спасибо, прошу прощения за непростительную в этом деле невнимательность. Перезалью как форк с лицензией.

Что же касается существования, нужно было лично мне.

На сём удаляю репо, и, при возможном наличии на то достаточных причин, форкаю. Спасибо за issue.
